%% Fig. 1  Dual-channel competition geometry
% MATLAB R2019b compatible
%
% The script only opens a figure window.
% It does not close existing figures or save output files.

clear;
clc;


%% ========================== APPEARANCE =================================

blue   = [0, 114, 178]/255;
orange = [213, 94, 0]/255;
dark   = [0.15, 0.15, 0.15];
gray   = [0.58, 0.58, 0.58];
lightGray = [0.84, 0.84, 0.84];

% Very light backgrounds for panel (a)
neutralTint = [0.975, 0.975, 0.975];
blueTint    = [0.950, 0.972, 0.987];
balanceTint = [0.980, 0.980, 0.980];
orangeTint  = [0.995, 0.960, 0.935];

% Backward-compatible Turbo colormap
cmap = turboR2019b(256);

% Full-page-width figure
figureWidth  = 18.0;      % cm
figureHeight = 9.8;       % cm

fig = figure( ...
    'Color', 'w', ...
    'Units', 'centimeters', ...
    'Position', [2, 2, figureWidth, figureHeight], ...
    'Renderer', 'painters', ...
    'InvertHardcopy', 'off');


%% ===================== REPRESENTATIVE STATES ===========================

betaState = [-0.80, 0.00, 0.80];
mState = sqrt(1-betaState.^2);

jPlusState  = (1+betaState)/2;
jMinusState = (1-betaState)/2;

assert(max(abs(betaState.^2+mState.^2-1)) < 1e-12, ...
    'The normalized state identity is not satisfied.');

assert(max(abs(jPlusState+jMinusState-1)) < 1e-12, ...
    'The normalized channel magnitudes do not sum to unity.');

assert(all(jPlusState >= 0) && all(jMinusState >= 0), ...
    'The channel magnitudes must be nonnegative.');


%% ============================= PANEL (a) ===============================
% One framed panel containing:
% channel schematic, state I, state II, and state III

axA = axes( ...
    'Parent', fig, ...
    'Position', [0.040, 0.675, 0.920, 0.265]);

hold(axA, 'on');

xlim(axA, [0, 1]);
ylim(axA, [0, 1]);
axis(axA, 'off');

% Panel label
text(axA, 0.000, 1.055, '(a)', ...
    'Units', 'normalized', ...
    'FontName', 'Arial', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'top', ...
    'Clipping', 'off');


%% ---------------------- Four framed compartments -----------------------

xEdge = [0.010, 0.245, 0.495, 0.745, 0.990];

boxBottom = 0.075;
boxHeight = 0.825;

cellColors = { ...
    neutralTint, ...
    blueTint, ...
    balanceTint, ...
    orangeTint};

% Draw four individual cells
for k = 1:4

    rectangle(axA, ...
        'Position', [ ...
        xEdge(k), ...
        boxBottom, ...
        xEdge(k+1)-xEdge(k), ...
        boxHeight], ...
        'FaceColor', cellColors{k}, ...
        'EdgeColor', lightGray, ...
        'LineWidth', 0.8);

end

% Draw one darker outer boundary around the entire subfigure
rectangle(axA, ...
    'Position', [ ...
    xEdge(1), ...
    boxBottom, ...
    xEdge(end)-xEdge(1), ...
    boxHeight], ...
    'FaceColor', 'none', ...
    'EdgeColor', [0.38, 0.38, 0.38], ...
    'LineWidth', 1.0);


%% ------------------------- Compartment centers -------------------------

cellCenter = 0.5*(xEdge(1:end-1)+xEdge(2:end));


%% ---------------------- First cell: channel schematic ------------------

text(axA, cellCenter(1), 0.785, ...
    'Dual-channel state', ...
    'FontName', 'Arial', ...
    'FontSize', 9.2, ...
    'FontWeight', 'bold', ...
    'Color', dark, ...
    'HorizontalAlignment', 'center');

% Use equal display lengths because this cell defines the two directions,
% rather than representing a particular state.
drawOpposingChannels( ...
    axA, ...
    cellCenter(1), ...
    0.445, ...
    0.70, ...
    0.70, ...
    0.105, ...
    blue, ...
    orange, ...
    dark);

text(axA, cellCenter(1)-0.067, 0.590, '$J_{-}$', ...
    'Interpreter', 'latex', ...
    'FontSize', 10, ...
    'Color', blue, ...
    'HorizontalAlignment', 'center');

text(axA, cellCenter(1)+0.067, 0.590, '$J_{+}$', ...
    'Interpreter', 'latex', ...
    'FontSize', 10, ...
    'Color', orange, ...
    'HorizontalAlignment', 'center');

text(axA, cellCenter(1), 0.205, ...
    'opposing contributions', ...
    'FontName', 'Arial', ...
    'FontSize', 8.2, ...
    'Color', gray, ...
    'HorizontalAlignment', 'center');


%% ---------------------- Remaining cells: states I-III ------------------

stateCenters = cellCenter(2:4);

stateTitles = { ...
    'I', ...
    'II', ...
    'III'};

stateDescriptions = { ...
    '$J_{-}$ dominant', ...
    'balanced active', ...
    '$J_{+}$ dominant'};

for k = 1:3

    text(axA, stateCenters(k), 0.790, stateTitles{k}, ...
        'FontName', 'Arial', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'Color', dark, ...
        'HorizontalAlignment', 'center');

    text(axA, stateCenters(k), 0.650, stateDescriptions{k}, ...
        'Interpreter', 'latex', ...
        'FontSize', 8.8, ...
        'Color', dark, ...
        'HorizontalAlignment', 'center');

    drawOpposingChannels( ...
        axA, ...
        stateCenters(k), ...
        0.415, ...
        jPlusState(k), ...
        jMinusState(k), ...
        0.105, ...
        blue, ...
        orange, ...
        dark);

end

% Small labels below the state diagrams
text(axA, stateCenters(1), 0.205, ...
    'negative dominance', ...
    'FontName', 'Arial', ...
    'FontSize', 8.2, ...
    'Color', gray, ...
    'HorizontalAlignment', 'center');

text(axA, stateCenters(2), 0.205, ...
    'exact balance', ...
    'FontName', 'Arial', ...
    'FontSize', 8.2, ...
    'Color', gray, ...
    'HorizontalAlignment', 'center');

text(axA, stateCenters(3), 0.205, ...
    'positive dominance', ...
    'FontName', 'Arial', ...
    'FontSize', 8.2, ...
    'Color', gray, ...
    'HorizontalAlignment', 'center');


%% ============================= PANEL (b) ===============================
% Dimensional state space and beta-colored illustrative state path

axBPosition = [0.070, 0.095, 0.350, 0.470];

axB = axes( ...
    'Parent', fig, ...
    'Position', axBPosition);

hold(axB, 'on');

Smax = 0.86;
Nmax = 1.08;

xlim(axB, [-Smax, Smax]);
ylim(axB, [0, Nmax]);


%% --------------------------- Constant-M curves -------------------------

Sgrid = linspace(-Smax, Smax, 801);
Mlevels = [0.12, 0.24, 0.36, 0.48, 0.60];

for k = 1:numel(Mlevels)

    Ngrid = sqrt(Sgrid.^2+Mlevels(k)^2);
    valid = Ngrid <= Nmax;

    plot(axB, Sgrid(valid), Ngrid(valid), '-', ...
        'Color', lightGray, ...
        'LineWidth', 0.85);

end


%% ----------------------- Single-channel boundaries ---------------------

plot(axB, [-Smax, 0], [Smax, 0], '--', ...
    'Color', [0.30, 0.30, 0.30], ...
    'LineWidth', 1.15);

plot(axB, [0, Smax], [0, Smax], '--', ...
    'Color', [0.30, 0.30, 0.30], ...
    'LineWidth', 1.15);

% Balanced-state axis
plot(axB, [0, 0], [0, Nmax], ':', ...
    'Color', [0.72, 0.72, 0.72], ...
    'LineWidth', 0.8);


%% ---------------------- Illustrative colored trajectory ----------------

trajectoryParameter = linspace(-1, 1, 501);

betaPath = ...
    0.985*tanh(2.1*trajectoryParameter)/tanh(2.1);

Npath = ...
    0.55 ...
    +0.40*exp(-(trajectoryParameter/0.70).^2) ...
    +0.05*(1+trajectoryParameter)/2;

Spath = betaPath.*Npath;
Mpath = Npath.*sqrt(max(0,1-betaPath.^2));

pathResidual = Npath.^2-Spath.^2-Mpath.^2;

assert(max(abs(pathResidual)) < 1e-12, ...
    'The illustrative path violates the dimensional identity.');

plotGradientLine( ...
    axB, ...
    Spath, ...
    Npath, ...
    betaPath, ...
    cmap, ...
    3.3);


%% ------------------------ Representative states -----------------------

% Exact path locations at beta=-0.8, 0, and +0.8
xState = atanh(betaState*tanh(2.1)/0.985)/2.1;

NstateDim = ...
    0.55 ...
    +0.40*exp(-(xState/0.70).^2) ...
    +0.05*(1+xState)/2;

SstateDim = betaState.*NstateDim;
MstateDim = mState.*NstateDim;

assert(max(abs( ...
    NstateDim.^2-SstateDim.^2-MstateDim.^2)) < 1e-12, ...
    'The representative dimensional states are inconsistent.');

plotStateMarker(axB, SstateDim(1), NstateDim(1), 'o', dark);
plotStateMarker(axB, SstateDim(2), NstateDim(2), 's', dark);
plotStateMarker(axB, SstateDim(3), NstateDim(3), '^', dark);

text(axB, SstateDim(1)-0.075, NstateDim(1)+0.050, 'I', ...
    'FontName', 'Arial', ...
    'FontSize', 9, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center');

text(axB, SstateDim(2)+0.070, NstateDim(2)+0.045, 'II', ...
    'FontName', 'Arial', ...
    'FontSize', 9, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center');

text(axB, SstateDim(3)+0.075, NstateDim(3)+0.050, 'III', ...
    'FontName', 'Arial', ...
    'FontSize', 9, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center');


%% ----------------------------- Axes ------------------------------------

xlabel(axB, '$S$', ...
    'Interpreter', 'latex', ...
    'FontSize', 10.5);

ylabel(axB, '$\mathcal{N}$', ...
    'Interpreter', 'latex', ...
    'FontSize', 10.5);

set(axB, ...
    'XTick', -0.8:0.4:0.8, ...
    'YTick', 0:0.2:1.0);

formatAxes(axB);

% S and N have identical dimensions
axis(axB, 'equal');

text(axB, -0.13, 1.105, '(b)', ...
    'Units', 'normalized', ...
    'FontName', 'Arial', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'Clipping', 'off');


%% ----------------------------- Colorbar --------------------------------

colormap(axB, cmap);
caxis(axB, [-1, 1]);

cb = colorbar(axB, 'eastoutside');

% Restore the desired axes dimensions
set(axB, 'Position', axBPosition);

set(cb, ...
    'Units', 'normalized', ...
    'Position', [0.430, 0.170, 0.012, 0.280], ...
    'FontName', 'Arial', ...
    'FontSize', 8, ...
    'Ticks', [-1, -0.5, 0, 0.5, 1]);

cb.Label.String = '\beta';
cb.Label.Interpreter = 'tex';
cb.Label.FontName = 'Arial';
cb.Label.FontSize = 10;


%% ============================= PANEL (c) ===============================
% Normalized state manifold

axC = axes( ...
    'Parent', fig, ...
    'Position', [0.555, 0.095, 0.390, 0.470]);

hold(axC, 'on');

betaArc = linspace(-1, 1, 801);
mArc = sqrt(max(0,1-betaArc.^2));

xlim(axC, [-1.05, 1.05]);
ylim(axC, [0, 1.08]);


%% -------------------------- Projection guides --------------------------

for k = [1, 3]

    plot(axC, ...
        [betaState(k), betaState(k)], ...
        [0, mState(k)], ...
        ':', ...
        'Color', lightGray, ...
        'LineWidth', 0.80);

    plot(axC, ...
        [0, betaState(k)], ...
        [mState(k), mState(k)], ...
        ':', ...
        'Color', lightGray, ...
        'LineWidth', 0.80);

end

plot(axC, [0, 0], [0, 1], ':', ...
    'Color', lightGray, ...
    'LineWidth', 0.80);


%% ----------------------- Colored state manifold ------------------------

plotGradientLine( ...
    axC, ...
    betaArc, ...
    mArc, ...
    betaArc, ...
    cmap, ...
    3.3);


%% ------------------------ Representative states -----------------------

plotStateMarker(axC, betaState(1), mState(1), 'o', dark);
plotStateMarker(axC, betaState(2), mState(2), 's', dark);
plotStateMarker(axC, betaState(3), mState(3), '^', dark);

text(axC, betaState(1)-0.10, mState(1)+0.060, 'I', ...
    'FontName', 'Arial', ...
    'FontSize', 9, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center');

text(axC, betaState(2)+0.075, mState(2)+0.045, 'II', ...
    'FontName', 'Arial', ...
    'FontSize', 9, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center');

text(axC, betaState(3)+0.10, mState(3)+0.060, 'III', ...
    'FontName', 'Arial', ...
    'FontSize', 9, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center');


%% ------------------------- Regime annotations --------------------------

text(axC, 0, 0.875, ...
    'balanced active', ...
    'FontName', 'Arial', ...
    'FontSize', 8.3, ...
    'Color', dark, ...
    'HorizontalAlignment', 'center');

text(axC, -0.69, 0.145, ...
    '$J_{-}$ dominance', ...
    'Interpreter', 'latex', ...
    'FontSize', 8.3, ...
    'Color', dark, ...
    'HorizontalAlignment', 'center');

text(axC, 0.69, 0.145, ...
    '$J_{+}$ dominance', ...
    'Interpreter', 'latex', ...
    'FontSize', 8.3, ...
    'Color', dark, ...
    'HorizontalAlignment', 'center');


%% ----------------------------- Axes ------------------------------------

xlabel(axC, '$\beta$', ...
    'Interpreter', 'latex', ...
    'FontSize', 10.5);

ylabel(axC, '$m$', ...
    'Interpreter', 'latex', ...
    'FontSize', 10.5);

set(axC, ...
    'XTick', -1:0.5:1, ...
    'YTick', 0:0.2:1.0);

formatAxes(axC);

% Preserve the true unit-semicircle geometry
axis(axC, 'equal');

text(axC, -0.13, 1.105, '(c)', ...
    'Units', 'normalized', ...
    'FontName', 'Arial', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'Clipping', 'off');


%% =========================== LOCAL FUNCTIONS ===========================

function drawOpposingChannels( ...
    ax, xCenter, yCenter, jPlus, jMinus, ...
    lengthScale, blue, orange, dark)
% Draw two opposing channel contributions from a common origin.

leftEnd  = xCenter-lengthScale*jMinus;
rightEnd = xCenter+lengthScale*jPlus;

% Channel lines
plot(ax, [xCenter, leftEnd], [yCenter, yCenter], '-', ...
    'Color', blue, ...
    'LineWidth', 4.0);

plot(ax, [xCenter, rightEnd], [yCenter, yCenter], '-', ...
    'Color', orange, ...
    'LineWidth', 4.0);

% Arrowhead dimensions in panel-(a) coordinates
headLength = 0.007;
headHeight = 0.024;

% Left arrowhead
patch(ax, ...
    [leftEnd, leftEnd+headLength, leftEnd+headLength], ...
    [yCenter, yCenter+headHeight, yCenter-headHeight], ...
    blue, ...
    'EdgeColor', blue);

% Right arrowhead
patch(ax, ...
    [rightEnd, rightEnd-headLength, rightEnd-headLength], ...
    [yCenter, yCenter+headHeight, yCenter-headHeight], ...
    orange, ...
    'EdgeColor', orange);

% Common origin
tickHeight = 0.040;

plot(ax, ...
    [xCenter, xCenter], ...
    [yCenter-tickHeight, yCenter+tickHeight], ...
    '-', ...
    'Color', dark, ...
    'LineWidth', 1.0);

end


function plotGradientLine(ax, x, y, colorVariable, cmap, lineWidth)
% Plot a curve with color determined by values between -1 and 1.

numberOfColors = size(cmap,1);

for k = 1:numel(x)-1

    colorIndex = 1+round( ...
        (numberOfColors-1)*(colorVariable(k)+1)/2);

    colorIndex = max(1,min(numberOfColors,colorIndex));

    plot(ax, ...
        x(k:k+1), ...
        y(k:k+1), ...
        '-', ...
        'Color', cmap(colorIndex,:), ...
        'LineWidth', lineWidth);

end

end


function plotStateMarker(ax, xValue, yValue, markerType, dark)
% Marker shapes provide identification independent of color.

plot(ax, xValue, yValue, ...
    'LineStyle', 'none', ...
    'Marker', markerType, ...
    'MarkerSize', 7.5, ...
    'MarkerFaceColor', 'w', ...
    'MarkerEdgeColor', dark, ...
    'LineWidth', 1.2);

end


function formatAxes(ax)
% Journal-style axes formatting.

set(ax, ...
    'FontName', 'Arial', ...
    'FontSize', 9, ...
    'LineWidth', 0.85, ...
    'TickDir', 'out', ...
    'TickLength', [0.018, 0.018], ...
    'Box', 'on', ...
    'Layer', 'top', ...
    'XColor', [0.12, 0.12, 0.12], ...
    'YColor', [0.12, 0.12, 0.12]);

grid(ax, 'off');

end


function cmap = turboR2019b(n)
% Backward-compatible Turbo colormap approximation.

if nargin < 1
    n = 256;
end

x = linspace(0,1,n)';

x2 = x.^2;
x3 = x.^3;
x4 = x.^4;
x5 = x.^5;

kRed = [ ...
     0.13572138, ...
     4.61539260, ...
   -42.66032258, ...
   132.13108234, ...
  -152.94239396, ...
    59.28637943];

kGreen = [ ...
     0.09140261, ...
     2.19418839, ...
     4.84296658, ...
   -14.18503333, ...
     4.27729857, ...
     2.82956604];

kBlue = [ ...
      0.10667330, ...
     12.64194608, ...
    -60.58204836, ...
    110.36276771, ...
    -89.90310912, ...
     27.34824973];

X = [ones(n,1), x, x2, x3, x4, x5];

redChannel   = X*kRed';
greenChannel = X*kGreen';
blueChannel  = X*kBlue';

cmap = [redChannel, greenChannel, blueChannel];

cmap(cmap < 0) = 0;
cmap(cmap > 1) = 1;

end