%% Fig. 5: Hydraulic performance diagnostics
% This script is self-contained. It evaluates the exact scalar expressions,
% locates the three characteristic filling states independently of the
% plotting grid, and draws the two-panel figure with a peak-region inset.

clear; clc; close all;

set(groot, ...
    'defaultAxesFontName','Arial', ...
    'defaultTextFontName','Arial');

%% 1. Numerical settings

Hmin = 0.01;
Hmax = 1.99;
H = linspace(Hmin,Hmax,401).';

optMain.kMax   = 12;
optMain.RelTol = 1.0e-10;
optMain.AbsTol = 1.0e-12;

optRef.kMax   = 16;
optRef.RelTol = 1.0e-12;
optRef.AbsTol = 1.0e-14;

%% 2. Evaluate the three diagnostics

nH = numel(H);
QFS = zeros(nH,1);
PiB = zeros(nH,1);
PiQ = zeros(nH,1);

for iH = 1:nH
    state = scalarState(H(iH),optMain);
    QFS(iH) = state.QFS;
    PiB(iH) = state.PiB;
    PiQ(iH) = state.PiQ;
end

Y = [QFS PiB PiQ];
metricNames = {'QFS','PiB','PiQ'};

%% 3. Locate the characteristic filling states

optSearch = optimset( ...
    'TolX',1.0e-10, ...
    'Display','off');

HQ = fminbnd( ...
    @(h) -metricValue(h,'QFS',optRef), ...
    Hmin,Hmax,optSearch);

HB = fminbnd( ...
    @(h) -metricValue(h,'PiB',optRef), ...
    Hmin,Hmax,optSearch);

HT = fminbnd( ...
    @(h) -metricValue(h,'PiQ',optRef), ...
    Hmin,Hmax,optSearch);

stateQ = scalarState(HQ,optRef);
stateB = scalarState(HB,optRef);
stateT = scalarState(HT,optRef);

Hstar = [HQ HB HT];
Ystar = [stateQ.QFS stateB.PiB stateT.PiQ];

%% 4. Normalize each diagnostic by its independently optimized maximum

Yn = bsxfun(@rdivide,Y,Ystar);

fprintf('\nCharacteristic filling states used in Fig. 5:\n');
fprintf('  H_Q^* = %.8f, Q_FS,max = %.8f\n',HQ,stateQ.QFS);
fprintf('  H_B^* = %.8f, Pi_B,max = %.8f\n',HB,stateB.PiB);
fprintf('  H_T^* = %.8f, Pi_Q,max = %.8f\n',HT,stateT.PiQ);

%% 5. Figure appearance

colors = [ ...
    0.00 0.32 0.72; ...
    0.80 0.15 0.12; ...
    0.12 0.12 0.12];

styles  = {'-', '--', '-.'};
markers = {'o', 's', '^'};

markerSize = 5.5;
markerLineWidth = 1.1;
curveLineWidth = 1.4;

labelsA = { ...
    '$Q_{\mathrm{FS}}$', ...
    '$\Pi_B$', ...
    '$\Pi_Q$'};

labelsB = { ...
    '$Q_{\mathrm{FS}}/Q_{\mathrm{FS},\max}$', ...
    '$\Pi_B/\Pi_{B,\max}$', ...
    '$\Pi_Q/\Pi_{Q,\max}$'};

fig = figure( ...
    'Color','w', ...
    'Name','Fig. 5', ...
    'NumberTitle','off', ...
    'Units','centimeters', ...
    'Position',[2 2 18.4 9.2], ...
    'Renderer','painters');

% 为顶部共用图例预留空间。
positions = [ ...
    0.092 0.160 0.365 0.650; ...
    0.607 0.160 0.365 0.650];

ax = gobjects(1,2);

for p = 1:2

    ax(p) = axes( ...
        'Parent',fig, ...
        'Position',positions(p,:));

    hold(ax(p),'on');

    set(ax(p), ...
        'FontName','Arial', ...
        'FontSize',9, ...
        'LineWidth',0.75, ...
        'TickDir','out', ...
        'TickLength',[0.018 0.018], ...
        'Box','on', ...
        'Layer','top', ...
        'XLim',[0 2], ...
        'XTick',0:0.5:2, ...
        'XMinorTick','off', ...
        'YMinorTick','off');

    xlabel(ax(p),'$H$', ...
        'Interpreter','latex', ...
        'FontSize',11);

end

%% 6. Panel (a): dimensionless values

ylim(ax(1),[0 0.55]);
yticks(ax(1),0:0.1:0.5);

% Half-filled reference state.
plot(ax(1),[1 1],[0 0.55], ...
    'LineStyle',':', ...
    'Color',[0.65 0.65 0.65], ...
    'LineWidth',0.8, ...
    'HandleVisibility','off');

% 先绘制全部曲线。
linesA = gobjects(1,3);

for j = 1:3

    linesA(j) = plot(ax(1),H,Y(:,j), ...
        'Color',colors(j,:), ...
        'LineStyle',styles{j}, ...
        'LineWidth',curveLineWidth);

end

% 再绘制极值标记，使标记位于曲线上方。
for j = 1:3

    plot(ax(1),Hstar(j),Ystar(j), ...
        'LineStyle','none', ...
        'Marker',markers{j}, ...
        'MarkerSize',markerSize, ...
        'MarkerEdgeColor',colors(j,:), ...
        'MarkerFaceColor','w', ...
        'LineWidth',markerLineWidth, ...
        'HandleVisibility','off');

end

ylabel(ax(1),'Dimensionless value', ...
    'FontName','Arial', ...
    'FontSize',10);

lgA = legend(ax(1),linesA,labelsA, ...
    'Interpreter','latex', ...
    'Location','northwest', ...
    'Box','off', ...
    'FontSize',9);

lgA.ItemTokenSize = [24 12];

text(ax(1),-0.13,1.07,'(a)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'Clipping','off');

%% 7. Panel (b): normalized responses

ylim(ax(2),[0 1.08]);
yticks(ax(2),0:0.2:1);

plot(ax(2),[1 1],[0 1.08], ...
    'LineStyle',':', ...
    'Color',[0.65 0.65 0.65], ...
    'LineWidth',0.8, ...
    'HandleVisibility','off');

% Normalized curves.
linesB = gobjects(1,3);

for j = 1:3

    linesB(j) = plot(ax(2),H,Yn(:,j), ...
        'Color',colors(j,:), ...
        'LineStyle',styles{j}, ...
        'LineWidth',curveLineWidth);

end

% 各曲线均以自身最大值归一化，因此极值纵坐标均为 1。
% 符号、颜色和尺寸与子图 (a) 完全一致。
for j = 1:3

    plot(ax(2),Hstar(j),1, ...
        'LineStyle','none', ...
        'Marker',markers{j}, ...
        'MarkerSize',markerSize, ...
        'MarkerEdgeColor',colors(j,:), ...
        'MarkerFaceColor','w', ...
        'LineWidth',markerLineWidth, ...
        'HandleVisibility','off');

end

ylabel(ax(2),'Normalized value', ...
    'FontName','Arial', ...
    'FontSize',10);

lgB = legend(ax(2),linesB,labelsB, ...
    'Interpreter','latex', ...
    'Location','northwest', ...
    'Box','off', ...
    'FontSize',9);

lgB.ItemTokenSize = [24 12];

text(ax(2),-0.13,1.07,'(b)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'Clipping','off');

%% 8. Peak-region inset in panel (b)

% The horizontal range follows the three optimized peak locations.
peakSpan = max(Hstar)-min(Hstar);
xPadding = max(0.035,0.12*peakSpan);
xZoom = [ ...
    max(Hmin,min(Hstar)-xPadding), ...
    min(Hmax,max(Hstar)+xPadding)];

% This range emphasizes the neighborhood of the normalized maxima.
% Reduce zoomYMin to 0.94 if a wider vertical context is desired.
zoomYMin = 0.96;
zoomYMax = 1.005;
yZoom = [zoomYMin zoomYMax];

% Mark the enlarged region on the main axes.
rectangle( ...
    'Parent',ax(2), ...
    'Position',[xZoom(1) yZoom(1) diff(xZoom) diff(yZoom)], ...
    'EdgeColor',[0.42 0.42 0.42], ...
    'LineStyle',':', ...
    'LineWidth',0.75, ...
    'FaceColor','none', ...
    'HandleVisibility','off');

% Place the inset in the lower-right part of panel (b).
axInset = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',[0.792 0.275 0.153 0.235], ...
    'Color','w', ...
    'FontName','Arial', ...
    'FontSize',7.2, ...
    'LineWidth',0.65, ...
    'TickDir','out', ...
    'TickLength',[0.025 0.025], ...
    'Box','on', ...
    'Layer','top', ...
    'XLim',xZoom, ...
    'YLim',yZoom, ...
    'XMinorTick','off', ...
    'YMinorTick','off');

hold(axInset,'on');

for j = 1:3
    plot(axInset,H,Yn(:,j), ...
        'Color',colors(j,:), ...
        'LineStyle',styles{j}, ...
        'LineWidth',1.05, ...
        'HandleVisibility','off');
end

for j = 1:3
    plot(axInset,Hstar(j),1, ...
        'LineStyle','none', ...
        'Marker',markers{j}, ...
        'MarkerSize',4.5, ...
        'MarkerEdgeColor',colors(j,:), ...
        'MarkerFaceColor','w', ...
        'LineWidth',0.9, ...
        'HandleVisibility','off');
end

set(axInset, ...
    'XTick',linspace(xZoom(1),xZoom(2),3), ...
    'YTick',[zoomYMin 0.98 1.00]);

xtickformat(axInset,'%.2f');
ytickformat(axInset,'%.2f');

%% 9. Shared marker legend above both panels
% 用隐藏坐标轴承载“真实标记 + 文字”。
% 不使用 Unicode 圆圈或三角形，避免字体导致符号外观不一致。

starLabels = { ...
    sprintf('$H_Q^* = %.4f$',Hstar(1)), ...
    sprintf('$H_B^* = %.4f$',Hstar(2)), ...
    sprintf('$H_T^* = %.4f$',Hstar(3))};

axKey = axes( ...
    'Parent',fig, ...
    'Units','normalized', ...
    'Position',[0.085 0.890 0.900 0.075], ...
    'XLim',[0 3], ...
    'YLim',[0 1], ...
    'Visible','off', ...
    'Color','none', ...
    'HitTest','off');

hold(axKey,'on');

for j = 1:3

    % 三项说明等间距横向排列。
    xMarker = (j-1)+0.12;
    xText   = xMarker+0.09;

    plot(axKey,xMarker,0.5, ...
        'LineStyle','none', ...
        'Marker',markers{j}, ...
        'MarkerSize',markerSize, ...
        'MarkerEdgeColor',colors(j,:), ...
        'MarkerFaceColor','w', ...
        'LineWidth',markerLineWidth, ...
        'HandleVisibility','off', ...
        'HitTest','off');

    text(axKey,xText,0.5,starLabels{j}, ...
        'Interpreter','latex', ...
        'FontSize',9.5, ...
        'Color',colors(j,:), ...
        'HorizontalAlignment','left', ...
        'VerticalAlignment','middle', ...
        'Clipping','off', ...
        'HitTest','off');

end

% 保留数值，不自动写入外部文件。
fig.UserData = struct( ...
    'H',H, ...
    'values',Y, ...
    'normalizedValues',Yn, ...
    'Hstar',Hstar, ...
    'maxima',Ystar, ...
    'metricNames',{metricNames}, ...
    'insetXLimits',xZoom, ...
    'insetYLimits',yZoom);

% 将当前坐标轴恢复为主子图。
set(fig,'CurrentAxes',ax(1));

drawnow;

%% Local functions

function state = scalarState(H,opt)

    alpha = acos(1-H);
    sa = sin(alpha);
    ca = cos(alpha);

    % Poisson-baseline discharge.
    QD = ...
        alpha/8 ...
        - sin(2*alpha)/12 ...
        + sin(4*alpha)/96;

    % Rigid-lid discharge.
    ID = integral( ...
        @(k) kernelID(k,alpha), ...
        0,opt.kMax, ...
        'RelTol',opt.RelTol, ...
        'AbsTol',opt.AbsTol);

    Qseg = ...
        cot(alpha)/6 ...
        + alpha/(8*sa^4) ...
        - ca*(5-2*ca^2)/(24*sa^3) ...
        - pi*ID;

    QRL = sa^4*Qseg;

    % Physical free-surface discharge.
    IN = integral( ...
        @(k) kernelIN(k,alpha), ...
        0,opt.kMax, ...
        'RelTol',opt.RelTol, ...
        'AbsTol',opt.AbsTol);

    QFS = ...
        (alpha ...
        - sin(2*alpha) ...
        + 0.25*sin(4*alpha) ...
        + 2*pi*sin(2*alpha)^2*IN)/8;

    % Boundary competition channels.
    CQ = QD-QRL;
    RQ = QFS-QRL;
    SB = RQ-CQ;

    PiB = SB^2/max(RQ,CQ);

    % Whole-transport competition channels.
    JplusQ = QD+RQ;
    PiQ = QFS^2/JplusQ;

    state.QD  = QD;
    state.QRL = QRL;
    state.QFS = QFS;
    state.CQ  = CQ;
    state.RQ  = RQ;
    state.SB  = SB;
    state.PiB = PiB;
    state.PiQ = PiQ;

end


function y = kernelID(k,alpha)

    y = zeros(size(k));
    small = abs(k)<1.0e-7;
    large = ~small;

    % Exact limit as k approaches zero.
    y(small) = 1/(alpha*pi^2);

    kk = k(large);
    y(large) = ...
        kk.^3 ./ ...
        (tanh(alpha*kk).*sinh(pi*kk).^2);

end


function y = kernelIN(k,alpha)

    y = zeros(size(k));
    small = abs(k)<1.0e-7;
    large = ~small;

    % Exact limit as k approaches zero.
    y(small) = alpha/pi^2;

    kk = k(large);
    y(large) = ...
        kk.*tanh(alpha*kk) ./ ...
        sinh(pi*kk).^2;

end


function value = metricValue(H,name,opt)

    state = scalarState(H,opt);

    switch name
        case 'QFS'
            value = state.QFS;
        case 'PiB'
            value = state.PiB;
        case 'PiQ'
            value = state.PiQ;
        otherwise
            error('Unknown metric: %s',name);
    end

end
