%% Equal-discharge hydraulic states in a partially filled circular conduit
% This standalone MATLAB R2019b script compares two filling states that
% have the same physical discharge but different internal hydraulic states.
%
% Panels:
%   (a) physical velocity field at the lower filling ratio;
%   (b) physical velocity field at the higher filling ratio;
%   (c) wall-shear distributions along the normalized wetted perimeter;
%   (d) signed driving-confinement-release discharge components.
%
% The script opens a figure window and does not export files automatically.

clear;
clc;
close all;

set(groot,'defaultAxesFontName','Arial');
set(groot,'defaultTextFontName','Arial');

%% 1. Numerical settings

Hmin = 0.01;
Hmax = 1.99;
targetFraction = 0.95;

optMain.kMax   = 12;
optMain.RelTol = 1.0e-10;
optMain.AbsTol = 1.0e-12;

optRef.kMax   = 16;
optRef.RelTol = 1.0e-12;
optRef.AbsTol = 1.0e-14;

optSearch = optimset( ...
    'TolX',1.0e-11, ...
    'Display','off');

% Field-resolution settings.
fieldSettings.ns    = 121;
fieldSettings.nxi   = 321;
fieldSettings.nk    = 900;
fieldSettings.xiMax = 7.0;
fieldSettings.kMax  = 12.0;

% Wall-shear settings. The analytical derivative is evaluated directly.
wallSettings.nxi   = 501;
wallSettings.nk    = 1800;
wallSettings.xiMax = 9.0;
wallSettings.kMax  = 14.0;

%% 2. Locate two states with the same physical discharge

HQ = fminbnd( ...
    @(h) -metricValue(h,'QFS',optRef), ...
    Hmin,Hmax,optSearch);

statePeak = scalarState(HQ,optRef);
Qtarget = targetFraction*statePeak.QFS;

equalDischargeResidual = ...
    @(h) scalarState(h,optRef).QFS-Qtarget;

leftBracket = [Hmin HQ];
rightBracket = [HQ Hmax];

assert( ...
    equalDischargeResidual(leftBracket(1))* ...
    equalDischargeResidual(leftBracket(2)) <= 0, ...
    'The lower-branch equal-discharge root is not bracketed.');

assert( ...
    equalDischargeResidual(rightBracket(1))* ...
    equalDischargeResidual(rightBracket(2)) <= 0, ...
    'The upper-branch equal-discharge root is not bracketed.');

HA = fzero(equalDischargeResidual,leftBracket,optSearch);
HB = fzero(equalDischargeResidual,rightBracket,optSearch);

SA = scalarState(HA,optRef);
SB = scalarState(HB,optRef);

%% 3. Evaluate velocity fields and wall shear

fieldA = dcrField(HA,fieldSettings);
fieldB = dcrField(HB,fieldSettings);

wallA = wallShear(HA,wallSettings);
wallB = wallShear(HB,wallSettings);

%% 4. Physical and numerical verification

equalDischargeRelativeError = ...
    abs(SA.QFS-SB.QFS)/max(abs(Qtarget),eps);

closureErrorA = ...
    abs(SA.QFS-(SA.QD-SA.CQ+SA.RQ));

closureErrorB = ...
    abs(SB.QFS-(SB.QD-SB.CQ+SB.RQ));

fieldWallErrorA = max(abs(fieldA.UFS(end,:)));
fieldWallErrorB = max(abs(fieldB.UFS(end,:)));

fieldSymmetryDifferenceA = ...
    fieldA.UFS-fliplr(fieldA.UFS);

fieldSymmetryDifferenceB = ...
    fieldB.UFS-fliplr(fieldB.UFS);

fieldSymmetryErrorA = ...
    max(abs(fieldSymmetryDifferenceA(:))) / ...
    max(max(abs(fieldA.UFS(:))),eps);

fieldSymmetryErrorB = ...
    max(abs(fieldSymmetryDifferenceB(:))) / ...
    max(max(abs(fieldB.UFS(:))),eps);

wallSymmetryErrorA = ...
    max(abs(wallA.Tw-fliplr(wallA.Tw))) / ...
    max(max(abs(wallA.Tw)),eps);

wallSymmetryErrorB = ...
    max(abs(wallB.Tw-fliplr(wallB.Tw))) / ...
    max(max(abs(wallB.Tw)),eps);

areaA = SA.alpha-0.5*sin(2*SA.alpha);
areaB = SB.alpha-0.5*sin(2*SB.alpha);

momentumErrorA = ...
    abs(wallA.integratedShear-areaA)/areaA;

momentumErrorB = ...
    abs(wallB.integratedShear-areaB)/areaB;

assert(equalDischargeRelativeError < 1.0e-8, ...
    'Equal-discharge check failed.');

assert(closureErrorA < 1.0e-9, ...
    'State A discharge closure failed.');

assert(closureErrorB < 1.0e-9, ...
    'State B discharge closure failed.');

assert(SA.CQ >= -1.0e-12 && SA.RQ >= -1.0e-12 && ...
       SB.CQ >= -1.0e-12 && SB.RQ >= -1.0e-12, ...
    'Integrated channel nonnegativity check failed.');

assert(fieldWallErrorA < 1.0e-9 && fieldWallErrorB < 1.0e-9, ...
    'The reconstructed velocity does not satisfy the no-slip wall.');

assert(fieldSymmetryErrorA < 1.0e-9 && ...
       fieldSymmetryErrorB < 1.0e-9, ...
    'Velocity-field symmetry check failed.');

assert(wallSymmetryErrorA < 1.0e-9 && ...
       wallSymmetryErrorB < 1.0e-9, ...
    'Wall-shear symmetry check failed.');

assert(momentumErrorA < 5.0e-3 && momentumErrorB < 5.0e-3, ...
    'Integrated wall shear does not satisfy the momentum balance.');

%% 5. Report the two states

fprintf('\nEqual-discharge hydraulic states\n');
fprintf('--------------------------------\n');
fprintf('Maximum discharge state: H_Q^* = %.8f\n',HQ);
fprintf('Target discharge: Q_FS = %.8f = %.2f Q_FS,max\n', ...
    Qtarget,targetFraction);
fprintf('\n');

printState('State A',HA,SA);
printState('State B',HB,SB);

fprintf('Relative equal-discharge error = %.3e\n', ...
    equalDischargeRelativeError);
fprintf('Discharge closure error, A     = %.3e\n',closureErrorA);
fprintf('Discharge closure error, B     = %.3e\n',closureErrorB);
fprintf('Wall-shear momentum error, A   = %.3e\n',momentumErrorA);
fprintf('Wall-shear momentum error, B   = %.3e\n',momentumErrorB);
fprintf('Wall-shear symmetry error, A   = %.3e\n',wallSymmetryErrorA);
fprintf('Wall-shear symmetry error, B   = %.3e\n',wallSymmetryErrorB);

%% 6. Figure appearance

colorA = [0.00 0.32 0.72];
colorB = [0.80 0.15 0.12];
colorDrive = [0.30 0.48 0.72];
colorRelease = [0.35 0.62 0.43];
colorConfinement = [0.76 0.30 0.27];

fig = figure( ...
    'Color','w', ...
    'Name','Equal-discharge hydraulic states', ...
    'NumberTitle','off', ...
    'Units','centimeters', ...
    'Position',[2 2 18.4 13.0], ...
    'Renderer','opengl');

axVelocityA = axes( ...
    'Parent',fig, ...
    'Position',[0.035 0.545 0.340 0.400]);

axVelocityB = axes( ...
    'Parent',fig, ...
    'Position',[0.495 0.545 0.340 0.400]);

axShear = axes( ...
    'Parent',fig, ...
    'Position',[0.080 0.100 0.390 0.325]);

axComponents = axes( ...
    'Parent',fig, ...
    'Position',[0.590 0.100 0.370 0.325]);

allAxes = [axVelocityA axVelocityB axShear axComponents];
for iAxis = 1:numel(allAxes)
    try
        allAxes(iAxis).Toolbar.Visible = 'off';
    catch
        % Axes toolbars are unavailable in some older MATLAB releases.
    end
end

velocityMaximum = max([fieldA.UFS(:);fieldB.UFS(:)]);
velocityLimits = [0 velocityMaximum];

drawVelocityPanel( ...
    axVelocityA,fieldA,velocityLimits,'(a)',HA);

drawVelocityPanel( ...
    axVelocityB,fieldB,velocityLimits,'(b)',HB);

colormap(fig,turboR2019b(256));

velocityTicks = linspace(velocityLimits(1),velocityLimits(2),4);

cbA = colorbar(axVelocityA);
cbA.Units = 'normalized';
cbA.Position = [0.380 0.615 0.012 0.255];
cbA.FontName = 'Arial';
cbA.FontSize = 8;
cbA.Ticks = velocityTicks;
cbA.Label.Interpreter = 'latex';
cbA.Label.String = '$U_{\mathrm{FS}}$';
cbA.Label.FontSize = 10;

cbB = colorbar(axVelocityB);
cbB.Units = 'normalized';
cbB.Position = [0.840 0.615 0.012 0.255];
cbB.FontName = 'Arial';
cbB.FontSize = 8;
cbB.Ticks = velocityTicks;
cbB.Label.Interpreter = 'latex';
cbB.Label.String = '$U_{\mathrm{FS}}$';
cbB.Label.FontSize = 10;

%% 7. Panel (c): wall shear

hold(axShear,'on');
box(axShear,'on');

positiveWallShear = [wallA.Tw(:);wallB.Tw(:)];
assert(all(isfinite(positiveWallShear)) && all(positiveWallShear>0), ...
    'Wall-shear values must be finite and positive for logarithmic plotting.');

semilogy(axShear,wallA.normalizedArc,wallA.Tw, ...
    '-', ...
    'Color',colorA, ...
    'LineWidth',1.5, ...
    'DisplayName',sprintf('$H=%.4f$',HA));

semilogy(axShear,wallB.normalizedArc,wallB.Tw, ...
    '--', ...
    'Color',colorB, ...
    'LineWidth',1.5, ...
    'DisplayName',sprintf('$H=%.4f$',HB));

xlabel(axShear,'$\ell/P_w$', ...
    'Interpreter','latex', ...
    'FontSize',10);

ylabel(axShear,'$T_w=-\partial U_{\mathrm{FS}}/\partial n$', ...
    'Interpreter','latex', ...
    'FontSize',10);

xlim(axShear,[0 1]);

wallShearLimits = [ ...
    0.85*min(positiveWallShear) ...
    1.15*max(positiveWallShear)];
ylim(axShear,wallShearLimits);

set(axShear, ...
    'YScale','log', ...
    'FontName','Arial', ...
    'FontSize',8.5, ...
    'LineWidth',0.75, ...
    'TickDir','out', ...
    'TickLength',[0.018 0.018], ...
    'Layer','top');

legend(axShear, ...
    'Interpreter','latex', ...
    'Location','north', ...
    'Box','off', ...
    'FontSize',8);

text(axShear,0.02,0.96,'(c)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'VerticalAlignment','top', ...
    'Clipping','on');

%% 8. Panel (d): signed discharge composition

hold(axComponents,'on');
box(axComponents,'on');

xState = [1 2];

componentValues = [ ...
    SA.QD -SA.CQ SA.RQ; ...
    SB.QD -SB.CQ SB.RQ];

netDischarge = [SA.QFS;SB.QFS];

componentBars = bar( ...
    axComponents,xState,componentValues,0.72,'grouped');

componentBars(1).FaceColor = colorDrive;
componentBars(1).EdgeColor = 'none';
componentBars(2).FaceColor = colorConfinement;
componentBars(2).EdgeColor = 'none';
componentBars(3).FaceColor = colorRelease;
componentBars(3).EdgeColor = 'none';

netMarkers = plot( ...
    axComponents,xState,netDischarge, ...
    'kd', ...
    'MarkerFaceColor','w', ...
    'MarkerSize',6, ...
    'LineWidth',1.1, ...
    'LineStyle','none');

plot(axComponents,[0.55 2.45],[Qtarget Qtarget], ...
    ':', ...
    'Color',[0.30 0.30 0.30], ...
    'LineWidth',0.8, ...
    'HandleVisibility','off');

plot(axComponents,[0.55 2.45],[0 0], ...
    '-', ...
    'Color',[0.25 0.25 0.25], ...
    'LineWidth',0.7, ...
    'HandleVisibility','off');

set(axComponents, ...
    'XLim',[0.55 2.45], ...
    'XTick',xState, ...
    'XTickLabel',{sprintf('$H=%.4f$',HA),sprintf('$H=%.4f$',HB)}, ...
    'TickLabelInterpreter','latex', ...
    'FontName','Arial', ...
    'FontSize',8.5, ...
    'LineWidth',0.75, ...
    'TickDir','out', ...
    'TickLength',[0.018 0.018], ...
    'Layer','top');

yMaximum = 1.18*max([componentValues(:);netDischarge(:)]);
yMinimum = 1.25*min(componentValues(:));
ylim(axComponents,[yMinimum yMaximum]);

ylabel(axComponents,'Dimensionless discharge contribution', ...
    'FontName','Arial', ...
    'FontSize',10);

legend(axComponents, ...
    [componentBars(1),componentBars(2),componentBars(3),netMarkers], ...
    {'$Q_D$','$-C_Q$','$R_Q$','$Q_{\mathrm{FS}}$'}, ...
    'Interpreter','latex', ...
    'Location','northoutside', ...
    'Orientation','horizontal', ...
    'Box','off', ...
    'FontSize',8);

text(axComponents,0.02,0.96,'(d)', ...
    'Units','normalized', ...
    'FontName','Arial', ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'VerticalAlignment','top', ...
    'Clipping','on');

%% 9. Preserve results in the figure object

fig.UserData = struct( ...
    'targetFraction',targetFraction, ...
    'Qtarget',Qtarget, ...
    'Hpeak',HQ, ...
    'HA',HA, ...
    'HB',HB, ...
    'stateA',SA, ...
    'stateB',SB, ...
    'fieldA',fieldA, ...
    'fieldB',fieldB, ...
    'wallA',wallA, ...
    'wallB',wallB, ...
    'equalDischargeRelativeError',equalDischargeRelativeError, ...
    'closureErrorA',closureErrorA, ...
    'closureErrorB',closureErrorB, ...
    'momentumErrorA',momentumErrorA, ...
    'momentumErrorB',momentumErrorB);

set(fig,'CurrentAxes',axVelocityA);
drawnow;

%% Local functions

function state = scalarState(H,opt)

    alpha = acos(1-H);
    sa = sin(alpha);
    ca = cos(alpha);

    QD = ...
        alpha/8 ...
        - sin(2*alpha)/12 ...
        + sin(4*alpha)/96;

    ID = integral( ...
        @(k) kernelID(k,alpha), ...
        0,opt.kMax, ...
        'RelTol',opt.RelTol, ...
        'AbsTol',opt.AbsTol);

    Qseg = ...
        cot(alpha)/6 ...
        + alpha/(8*sa^4) ...
        - ca*(5-2*ca^2)/(24*sa^3) ...
        - pi*ID;

    QRL = sa^4*Qseg;

    IN = integral( ...
        @(k) kernelIN(k,alpha), ...
        0,opt.kMax, ...
        'RelTol',opt.RelTol, ...
        'AbsTol',opt.AbsTol);

    QFS = ...
        (alpha ...
        - sin(2*alpha) ...
        + 0.25*sin(4*alpha) ...
        + 2*pi*sin(2*alpha)^2*IN)/8;

    QC = QRL-QD;
    QR = QFS-QRL;

    CQ = -QC;
    RQ = QR;
    SB = RQ-CQ;
    NB = RQ+CQ;

    betaB = SB/NB;
    mB = 2*sqrt(max(RQ*CQ,0))/NB;
    rhoB = sqrt(min(RQ,CQ)/max(RQ,CQ));

    JplusQ = QD+RQ;
    JminusQ = CQ;

    PiB = SB^2/max(RQ,CQ);
    PiQ = QFS^2/JplusQ;

    state = struct( ...
        'H',H, ...
        'alpha',alpha, ...
        'QD',QD, ...
        'QRL',QRL, ...
        'QFS',QFS, ...
        'QC',QC, ...
        'QR',QR, ...
        'CQ',CQ, ...
        'RQ',RQ, ...
        'SB',SB, ...
        'NB',NB, ...
        'betaB',betaB, ...
        'mB',mB, ...
        'rhoB',rhoB, ...
        'JplusQ',JplusQ, ...
        'JminusQ',JminusQ, ...
        'PiB',PiB, ...
        'PiQ',PiQ);

end


function field = dcrField(H,settings)

    alpha = acos(1-H);

    xi = linspace(-settings.xiMax,settings.xiMax,settings.nxi);
    s = linspace(0,1,settings.ns);
    [XI,S] = meshgrid(xi,s);

    den = cosh(XI)+cos(alpha*S);

    X = sin(alpha).*sinh(XI)./den;
    Y = -sin(alpha).*sin(alpha*S)./den;
    Yc = Y-cos(alpha);

    UD = ...
        sin(alpha).*sin(alpha*(1-S)) ./ ...
        (2*den);

    k = linspace(1.0e-5,settings.kMax,settings.nk);
    dk = k(2)-k(1);

    weights = ones(size(k));
    weights([1 end]) = 0.5;
    weights = weights*dk;

    UC = zeros(size(XI));
    chiN = zeros(size(XI));

    for q = 1:settings.nk

        kk = k(q);
        cosineMode = cos(kk*xi);
        verticalMode = sinh(kk*alpha*(1-s)).';
        modeShape = verticalMode*cosineMode;

        confinementCoefficient = ...
            -sin(alpha)^2*kk / ...
            (sinh(pi*kk)*sinh(alpha*kk));

        mixedCoefficient = ...
            -0.5*sin(2*alpha) / ...
            (sinh(pi*kk)*cosh(alpha*kk));

        UC = UC + ...
            weights(q)*confinementCoefficient*modeShape;

        chiN = chiN + ...
            weights(q)*mixedCoefficient*modeShape;

    end

    UR = chiN-UC;
    UFS = UD+UC+UR;

    field = struct( ...
        'H',H, ...
        'alpha',alpha, ...
        'xi',xi, ...
        's',s, ...
        'X',X, ...
        'Yc',Yc, ...
        'UD',UD, ...
        'UC',UC, ...
        'UR',UR, ...
        'C',-UC, ...
        'R',UR, ...
        'UFS',UFS);

end


function wall = wallShear(H,settings)

    alpha = acos(1-H);
    xi = linspace(-settings.xiMax,settings.xiMax,settings.nxi);
    k = linspace(1.0e-5,settings.kMax,settings.nk).';

    Dwall = cosh(xi)+cos(alpha);

    spectralCoefficient = ...
        k ./ (sinh(pi*k).*cosh(alpha*k));

    cosineModes = cos(k*xi);
    wallIntegral = trapz( ...
        k, ...
        bsxfun(@times,spectralCoefficient,cosineModes), ...
        1);

    % T_w=-dU_FS/dn. The first term is the Poisson contribution and the
    % second is the exact mixed-boundary correction at the circular wall.
    Tw = 0.5-Dwall.*cos(alpha).*wallIntegral;

    Xwall = sin(alpha).*sinh(xi)./Dwall;
    Ywall = -sin(alpha)^2./Dwall-cos(alpha);

    segmentLength = hypot(diff(Xwall),diff(Ywall));
    arcLength = [0 cumsum(segmentLength)];
    normalizedArc = arcLength/arcLength(end);

    integratedShear = trapz(arcLength,Tw);

    wall = struct( ...
        'H',H, ...
        'alpha',alpha, ...
        'xi',xi, ...
        'X',Xwall, ...
        'Yc',Ywall, ...
        'arcLength',arcLength, ...
        'normalizedArc',normalizedArc, ...
        'Tw',Tw, ...
        'integratedShear',integratedShear);

end


function value = metricValue(H,name,opt)

    state = scalarState(H,opt);

    switch name
        case 'QFS'
            value = state.QFS;
        case 'PiB'
            value = state.PiB;
        case 'PiQ'
            value = state.PiQ;
        otherwise
            error('Unknown metric: %s',name);
    end

end


function y = kernelID(k,alpha)

    y = zeros(size(k));
    small = abs(k)<1.0e-7;
    large = ~small;

    y(small) = 1/(alpha*pi^2);

    kk = k(large);
    y(large) = ...
        kk.^3 ./ ...
        (tanh(alpha*kk).*sinh(pi*kk).^2);

end


function y = kernelIN(k,alpha)

    y = zeros(size(k));
    small = abs(k)<1.0e-7;
    large = ~small;

    y(small) = alpha/pi^2;

    kk = k(large);
    y(large) = ...
        kk.*tanh(alpha*kk) ./ ...
        sinh(pi*kk).^2;

end


function drawVelocityPanel(ax,field,colorLimits,panelLabel,H)

    hold(ax,'on');

    plottedVelocity = max(field.UFS,0);

    surf( ...
        ax, ...
        field.X, ...
        field.Yc, ...
        zeros(size(plottedVelocity)), ...
        plottedVelocity, ...
        'EdgeColor','none');

    view(ax,2);
    axis(ax,'equal');
    axis(ax,'off');

    theta = linspace(0,2*pi,600);
    plot(ax,cos(theta),sin(theta), ...
        'k', ...
        'LineWidth',0.9);

    yFreeSurface = -cos(field.alpha);
    xEnd = sqrt(max(0,1-yFreeSurface^2));

    plot(ax,[-xEnd xEnd],[yFreeSurface yFreeSurface], ...
        '--', ...
        'Color',[0.25 0.25 0.25], ...
        'LineWidth',0.8);

    text(ax,0,yFreeSurface+0.040, ...
        sprintf('$H=%.4f$',H), ...
        'Interpreter','latex', ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontName','Arial', ...
        'FontSize',9, ...
        'Color',[0.10 0.10 0.10], ...
        'Clipping','on');

    xlim(ax,[-1.05 1.05]);
    ylim(ax,[-1.05 1.05]);
    caxis(ax,colorLimits);

    text(ax,0.02,0.98,panelLabel, ...
        'Units','normalized', ...
        'FontName','Arial', ...
        'FontSize',11, ...
        'FontWeight','bold', ...
        'VerticalAlignment','top', ...
        'Clipping','on');

end


function printState(label,H,state)

    fprintf('%s: H = %.8f\n',label,H);
    fprintf('  Q_FS   = %.10f\n',state.QFS);
    fprintf('  Q_D    = %.10f\n',state.QD);
    fprintf('  C_Q    = %.10f\n',state.CQ);
    fprintf('  R_Q    = %.10f\n',state.RQ);
    fprintf('  S_B    = %.10f\n',state.SB);
    fprintf('  beta_B = %.10f\n',state.betaB);
    fprintf('  m_B    = %.10f\n',state.mB);
    fprintf('\n');

end


function cmap = turboR2019b(n)

    if nargin<1
        n = 256;
    end

    x = linspace(0,1,n).';
    basis = [ones(n,1) x x.^2 x.^3 x.^4 x.^5];

    redCoefficients = [ ...
        0.13572138 4.61539260 -42.66032258 ...
        132.13108234 -152.94239396 59.28637943];

    greenCoefficients = [ ...
        0.09140261 2.19418839 4.84296658 ...
        -14.18503333 4.27729857 2.82956604];

    blueCoefficients = [ ...
        0.10667330 12.64194608 -60.58204836 ...
        110.36276771 -89.90310912 27.34824973];

    cmap = [ ...
        basis*redCoefficients.' ...
        basis*greenCoefficients.' ...
        basis*blueCoefficients.'];

    cmap = min(max(cmap,0),1);

end
