%% Fig7_cross_model_comparison.m
% Analytical comparison of three dual-channel realizations:
%   1. Plane Couette-Poiseuille flow
%   2. Opposing-shear Nusselt-film flow
%   3. Partially filled circular-conduit boundary subsystem
%
% MATLAB R2019b compatible.
% This script only opens a figure window. It does not export any files.

clear;
clc;

%% ------------------------------------------------------------------------
% Figure settings
% -------------------------------------------------------------------------

fontName  = 'Arial';
fontSize  = 11;
labelSize = 12;
lineWidth = 1.7;

% MATLAB default colors, distinguishable by both color and line style
cBlue   = [0.0000, 0.4470, 0.7410];
cOrange = [0.8500, 0.3250, 0.0980];
cGold   = [0.9290, 0.6940, 0.1250];
cPurple = [0.4940, 0.1840, 0.5560];
cGreen  = [0.4660, 0.6740, 0.1880];
cGray   = [0.35, 0.35, 0.35];

fig = figure( ...
    'Color', 'w', ...
    'Units', 'centimeters', ...
    'Position', [3, 2, 18.0, 15.5], ...
    'Renderer', 'painters', ...
    'Name', 'Fig. 7: Analytical Comparison across Canonical Flows', ...
    'NumberTitle', 'off');

%% ------------------------------------------------------------------------
% Universal normalized relations
% -------------------------------------------------------------------------

rho = linspace(0, 1, 600);

% Normalization by J_ref = max(J_+,J_-)
JdomHat = ones(size(rho));
JsubHat = rho.^2;

% Normalized activity, signed response, and interaction
Nhat     = 1 + rho.^2;
Mhat     = 2 .* rho;
ShatPos  = 1 - rho.^2;
ShatNeg  = -(1 - rho.^2);

% Unit-semicircle coordinates
betaPos = ShatPos ./ Nhat;
betaNeg = ShatNeg ./ Nhat;
m       = Mhat ./ Nhat;

% Algebraic consistency check
semicircleResidual = max(abs(betaPos.^2 + m.^2 - 1));

if semicircleResidual > 1e-12
    warning('Normalized-state identity residual is %.3e.', ...
        semicircleResidual);
end

%% ------------------------------------------------------------------------
% Panel (a): Normalized channel magnitudes
% -------------------------------------------------------------------------

ax1 = axes(fig, 'Position', [0.10, 0.57, 0.36, 0.34]);
hold(ax1, 'on');

plot(ax1, rho, JdomHat, ...
    '-', ...
    'Color', cBlue, ...
    'LineWidth', lineWidth, ...
    'DisplayName', ...
    '$J_{\mathrm{dom}}/J_{\mathrm{ref}}=1$');

plot(ax1, rho, JsubHat, ...
    '--', ...
    'Color', cOrange, ...
    'LineWidth', lineWidth, ...
    'DisplayName', ...
    '$J_{\mathrm{sub}}/J_{\mathrm{ref}}=\rho^2$');

xlabel(ax1, '$\rho$', ...
    'Interpreter', 'latex', ...
    'FontSize', labelSize);

ylabel(ax1, 'Normalized channel magnitude', ...
    'FontSize', labelSize);

xlim(ax1, [0, 1]);
ylim(ax1, [0, 1.06]);

legend(ax1, ...
    'Interpreter', 'latex', ...
    'Location', 'northwest', ...
    'Box', 'off', ...
    'FontSize', 9.5);

formatAxis(ax1, fontName, fontSize);

text(ax1, -0.15, 1.07, '(a)', ...
    'Units', 'normalized', ...
    'FontName', fontName, ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'bottom', ...
    'Clipping', 'off');

%% ------------------------------------------------------------------------
% Panel (b): Normalized activity, signed response, and interaction
% -------------------------------------------------------------------------

ax2 = axes(fig, 'Position', [0.58, 0.57, 0.36, 0.34]);
hold(ax2, 'on');

plot(ax2, rho, Nhat, ...
    '-', ...
    'Color', cBlue, ...
    'LineWidth', lineWidth, ...
    'DisplayName', ...
    '$\widehat{\mathcal{N}}=1+\rho^2$');

plot(ax2, rho, Mhat, ...
    '--', ...
    'Color', cOrange, ...
    'LineWidth', lineWidth, ...
    'DisplayName', ...
    '$\widehat{M}=2\rho$');

plot(ax2, rho, ShatPos, ...
    '-.', ...
    'Color', cGold, ...
    'LineWidth', lineWidth, ...
    'DisplayName', ...
    '$\widehat{S}=1-\rho^2$');

plot(ax2, rho, ShatNeg, ...
    ':', ...
    'Color', cPurple, ...
    'LineWidth', 2.0, ...
    'DisplayName', ...
    '$\widehat{S}=-(1-\rho^2)$');

yline(ax2, 0, ':', ...
    'Color', cGray, ...
    'LineWidth', 0.9, ...
    'HandleVisibility', 'off');

xlabel(ax2, '$\rho$', ...
    'Interpreter', 'latex', ...
    'FontSize', labelSize);

ylabel(ax2, 'State amplitude normalized by $J_{\mathrm{ref}}$', ...
    'Interpreter', 'latex', ...
    'FontSize', labelSize);

xlim(ax2, [0, 1]);
ylim(ax2, [-1.05, 2.05]);

legend(ax2, ...
    'Interpreter', 'latex', ...
    'Location', 'west', ...
    'Box', 'off', ...
    'FontSize', 9.0);

formatAxis(ax2, fontName, fontSize);

text(ax2, -0.15, 1.07, '(b)', ...
    'Units', 'normalized', ...
    'FontName', fontName, ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'bottom', ...
    'Clipping', 'off');

%% ------------------------------------------------------------------------
% Panel (c): Unit-semicircle state coordinates
% -------------------------------------------------------------------------

ax3 = axes(fig, 'Position', [0.10, 0.11, 0.36, 0.34]);
hold(ax3, 'on');

plot(ax3, rho, betaPos, ...
    '-', ...
    'Color', cBlue, ...
    'LineWidth', lineWidth, ...
    'DisplayName', ...
    '$\beta=(1-\rho^2)/(1+\rho^2)$');

plot(ax3, rho, betaNeg, ...
    '--', ...
    'Color', cOrange, ...
    'LineWidth', lineWidth, ...
    'DisplayName', ...
    '$\beta=-(1-\rho^2)/(1+\rho^2)$');

plot(ax3, rho, m, ...
    '-.', ...
    'Color', cGold, ...
    'LineWidth', lineWidth, ...
    'DisplayName', ...
    '$m=2\rho/(1+\rho^2)$');

yline(ax3, 0, ':', ...
    'Color', cGray, ...
    'LineWidth', 0.9, ...
    'HandleVisibility', 'off');

xlabel(ax3, '$\rho$', ...
    'Interpreter', 'latex', ...
    'FontSize', labelSize);

ylabel(ax3, 'Normalized state', ...
    'FontSize', labelSize);

xlim(ax3, [0, 1]);
ylim(ax3, [-1.05, 1.05]);

legend(ax3, ...
    'Interpreter', 'latex', ...
    'Location', 'southwest', ...
    'Box', 'off', ...
    'FontSize', 8.8);

formatAxis(ax3, fontName, fontSize);

text(ax3, -0.15, 1.07, '(c)', ...
    'Units', 'normalized', ...
    'FontName', fontName, ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'bottom', ...
    'Clipping', 'off');

%% ------------------------------------------------------------------------
% Panel (d): Native-control mappings
% -------------------------------------------------------------------------

% Couette-Poiseuille and Nusselt-film mappings
rhoControl = linspace(1e-3, 1, 1200);

% Pressure- or gravity-dominated branches
GammaC_low = rhoControl.^2 ./ 6;
GammaN_low = (2/3) .* rhoControl.^2;

% Opposing-wall- or opposing-shear-dominated branches
GammaC_high = 1 ./ (6 .* rhoControl.^2);
GammaN_high = (2/3) ./ rhoControl.^2;

% Limit the plotted native-control range
yMaximum = 2.05;

validC = GammaC_high <= yMaximum;
validN = GammaN_high <= yMaximum;

% Partially filled conduit: calculate rho_B(H) from exact scalar fields.
% Separate arrays are used so that the confinement- and release-dominated
% branches meet at the exact half-filled state H = 1.
Hlower = linspace(0.03, 1.00, 121);
Hupper = linspace(1.00, 1.97, 121);

rhoBlower = zeros(size(Hlower));
rhoBupper = zeros(size(Hupper));

for i = 1:numel(Hlower)
    result = dcrScalar(Hlower(i));
    rhoBlower(i) = result.rhoB;
end

for i = 1:numel(Hupper)
    result = dcrScalar(Hupper(i));
    rhoBupper(i) = result.rhoB;
end

ax4 = axes(fig, 'Position', [0.58, 0.11, 0.36, 0.34]);
hold(ax4, 'on');

% Couette-Poiseuille branches
plot(ax4, rhoControl, GammaC_low, ...
    '-', ...
    'Color', cBlue, ...
    'LineWidth', lineWidth, ...
    'DisplayName', 'CP: $\Gamma_C$');

plot(ax4, rhoControl(validC), GammaC_high(validC), ...
    '-', ...
    'Color', cBlue, ...
    'LineWidth', lineWidth, ...
    'HandleVisibility', 'off');

% Nusselt-film branches
plot(ax4, rhoControl, GammaN_low, ...
    '--', ...
    'Color', cOrange, ...
    'LineWidth', lineWidth, ...
    'DisplayName', 'NF: $\Gamma_N$');

plot(ax4, rhoControl(validN), GammaN_high(validN), ...
    '--', ...
    'Color', cOrange, ...
    'LineWidth', lineWidth, ...
    'HandleVisibility', 'off');

% Partially filled conduit branches
plot(ax4, rhoBlower, Hlower, ...
    '-.', ...
    'Color', cGreen, ...
    'LineWidth', lineWidth, ...
    'DisplayName', 'Pipe: $H$');

plot(ax4, rhoBupper, Hupper, ...
    '-.', ...
    'Color', cGreen, ...
    'LineWidth', lineWidth, ...
    'HandleVisibility', 'off');

% Exact balance points
plot(ax4, 1, 1/6, ...
    'o', ...
    'MarkerSize', 4.5, ...
    'MarkerFaceColor', 'w', ...
    'MarkerEdgeColor', cBlue, ...
    'LineWidth', 1.0, ...
    'HandleVisibility', 'off');

plot(ax4, 1, 2/3, ...
    'o', ...
    'MarkerSize', 4.5, ...
    'MarkerFaceColor', 'w', ...
    'MarkerEdgeColor', cOrange, ...
    'LineWidth', 1.0, ...
    'HandleVisibility', 'off');

plot(ax4, 1, 1, ...
    'o', ...
    'MarkerSize', 4.5, ...
    'MarkerFaceColor', 'w', ...
    'MarkerEdgeColor', cGreen, ...
    'LineWidth', 1.0, ...
    'HandleVisibility', 'off');

xlabel(ax4, '$\rho$', ...
    'Interpreter', 'latex', ...
    'FontSize', labelSize);

ylabel(ax4, 'Native dimensionless control', ...
    'FontSize', labelSize);

xlim(ax4, [0, 1]);
ylim(ax4, [0, yMaximum]);

legend(ax4, ...
    'Interpreter', 'latex', ...
    'Location', 'northwest', ...
    'Box', 'off', ...
    'FontSize', 9.2);

formatAxis(ax4, fontName, fontSize);

text(ax4, -0.15, 1.07, '(d)', ...
    'Units', 'normalized', ...
    'FontName', fontName, ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'bottom', ...
    'Clipping', 'off');

drawnow;

%% ========================================================================
% Local functions
% ========================================================================

function result = dcrScalar(H)
% Exact scalar driving-confinement-release quantities for a partially
% filled circular conduit.

    alpha = acos(1 - H);

    ID = integral( ...
        @(k) integrandID(k, alpha), ...
        0, 12, ...
        'RelTol', 1e-9, ...
        'AbsTol', 1e-12);

    IN = integral( ...
        @(k) integrandIN(k, alpha), ...
        0, 12, ...
        'RelTol', 1e-9, ...
        'AbsTol', 1e-12);

    % Filling-dependent Poisson-baseline discharge
    QD = alpha/8 ...
       - sin(2*alpha)/12 ...
       + sin(4*alpha)/96;

    % Auxiliary rigid-chord discharge
    Qseg = cot(alpha)/6 ...
         + alpha/(8*sin(alpha)^4) ...
         - cos(alpha)*(5 - 2*cos(alpha)^2) ...
           /(24*sin(alpha)^3) ...
         - pi*ID;

    QRL = sin(alpha)^4 * Qseg;

    % Confinement correction
    QC = QRL - QD;

    % Physical shear-free discharge
    QFS = ( ...
        alpha ...
        - sin(2*alpha) ...
        + 0.25*sin(4*alpha) ...
        + 2*pi*sin(2*alpha)^2*IN) / 8;

    % Release contribution
    QR = QFS - QRL;

    % Nonnegative boundary-channel magnitudes
    CQ = -QC;
    RQ = QR;

    dominantChannel   = max(CQ, RQ);
    subordinateChannel = min(CQ, RQ);

    ratio = subordinateChannel / dominantChannel;

    % Protect the square root against roundoff-level excursions.
    ratio = min(max(ratio, 0), 1);

    rhoB = sqrt(ratio);

    result = struct( ...
        'QD',   QD, ...
        'QRL',  QRL, ...
        'QC',   QC, ...
        'QFS',  QFS, ...
        'QR',   QR, ...
        'CQ',   CQ, ...
        'RQ',   RQ, ...
        'rhoB', rhoB);
end

function value = integrandID(k, alpha)
% Stable evaluation of
% k^3/[tanh(alpha*k)*sinh(pi*k)^2].

    value = zeros(size(k));

    nearZero = k < 1e-6;
    value(nearZero) = 1/(alpha*pi^2);

    kz = k(~nearZero);

    value(~nearZero) = kz.^3 ./ ...
        (tanh(alpha*kz) .* sinh(pi*kz).^2);
end

function value = integrandIN(k, alpha)
% Stable evaluation of
% k*tanh(alpha*k)/sinh(pi*k)^2.

    value = zeros(size(k));

    nearZero = k < 1e-6;
    value(nearZero) = alpha/pi^2;

    kz = k(~nearZero);

    value(~nearZero) = kz .* tanh(alpha*kz) ./ ...
        sinh(pi*kz).^2;
end

function formatAxis(ax, fontName, fontSize)
% Apply a consistent manuscript-figure style.

    set(ax, ...
        'FontName', fontName, ...
        'FontSize', fontSize, ...
        'LineWidth', 0.8, ...
        'TickDir', 'out', ...
        'TickLength', [0.018, 0.018], ...
        'Box', 'on', ...
        'Layer', 'top');

    ax.XMinorTick = 'off';
    ax.YMinorTick = 'off';
end